"""change task.id to task.uuid

Revision ID: 5bd32f8b1456
Revises: f6fdc4d0d14b
Create Date: 2025-11-22 21:14:11.415087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd32f8b1456'
down_revision: Union[str, Sequence[str], None] = 'f6fdc4d0d14b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('uuid', sa.UUID(), nullable=False))
    op.drop_column('tasks', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False))
    op.drop_column('tasks', 'uuid')
    # ### end Alembic commands ###
